### PR TITLE
[Fix] Validate when multiple providers are defined

### LINKED ISSUE #448: k8gb allows to load multiple providers
k8gb allows to read multiple providers simultaneously, i.e.: Infoblox + NS1. It causes the DNSProvider factory returns nil. 

In order to this:
 - Only one DNS provider can be configured, otherwise fail in resolving stage. 
 - `NS1_ENABLED` is not cleaned in controller_test.go _(configureEnvVar,cleanup )_

### PR DESCRIPTION
**Pull request by kuritka**
resolves #448

 - `controller_test.go` was missing NS1EnabledKey in the cleanup() and configureEnvVar(), added
 
 - rewrite `depresolver.getEdgeDNSType()`, the function now coud return one more DNSType: `DNSTypeError`.
 `DNSTypeError` indicates depresolver found more than one provider. `DNSTypeError` generates validation error on k8gb startup. 
 
  - `DNSTypeNoEdgeDNS` is returned when no provider is not recognised. This state passes validation; @ytsarev, is that expected behavior ? 
  
 - functionality covered  by depresolver tests.

Signed-off-by: kuritka <kuritka@gmail.com>

### CODE REVIEW

File: controllers/depresolver/depresolver_config.go [hunk 1]
```diff
@@ -94,6 +94,9 @@ func (dr *DependencyResolver) validateConfig(config *Config) (err error) {
 	if config.Log.Format == NoFormat {
 		return fmt.Errorf("invalid '%s', allowed values ['','%s','%s']", LogFormatKey, JSONFormat, SimpleFormat)
 	}
+	if config.EdgeDNSType == DNSTypeError {
+		return fmt.Errorf("more than one EdgeDNS types recognised")
```
Comment (somaritane) [inline controllers/depresolver/depresolver_config.go:98]: @kuritka, It would be good to help user with information on which providers have been detected in configuration.

Comment (somaritane) [inline controllers/depresolver/depresolver_config.go:98]: Spelling fiix
```suggestion
		return fmt.Errorf("More than one EdgeDNS provider recognized")
```

**Comment by ytsarev** [comment]
@kuritka k8gb can operate without edgeDNS provider, e.g. in local scenario or in some edge case environments where zone delegation is configured outside of k8gb. So that's expected.

**Review by somaritane — CHANGES_REQUESTED** [review]

File: controllers/depresolver/depresolver_test.go [hunk 2]
```diff
@@ -629,19 +629,51 @@ func TestResolveGeoTagWithRepeatingExtGeoTags(t *testing.T) {
 	arrangeVariablesAndAssert(t, expected, assert.Error)
 }
 
-func TestRoute53IsEnabledAndInfobloxIsConfigured(t *testing.T) {
+func TestRoute53IsEnabledAndInfobloxAreConfigured(t *testing.T) {
```
Comment (ytsarev) [inline controllers/depresolver/depresolver_test.go:632]: why Infoblox `Are` Configured?

Comment (ytsarev) [reply controllers/depresolver/depresolver_test.go:632]: Maybe semantically it is `TestBothRoute53AndInfobloxAreEnabled` ?

**Review by ytsarev — CHANGES_REQUESTED** [review]
test naming comment/suggestion

File: controllers/depresolver/depresolver_config.go (hunk 1 above)
Comment (kuritka) [reply controllers/depresolver/depresolver_config.go:98]: Error string should not be capitalized, otherwise IDE prints warning, see: https://github.com/golang/go/wiki/CodeReviewComments#error-strings. 

Otherwise, fixing `provider recognized `

Comment (somaritane) [reply controllers/depresolver/depresolver_config.go:98]: Ah, right, this is error message, resolved.

Comment (kuritka) [reply controllers/depresolver/depresolver_config.go]: @somaritane , agreed, implemented, although it required more changes, primarily: [[1]](https://github.com/AbsaOSS/k8gb/pull/450/files#diff-ef477f235dc201dc9a8f7505e61107d1be845c695ed8d201e07939e2496ec2edR66-R75), [[2]](https://github.com/AbsaOSS/k8gb/pull/450/files#diff-b94e4b6c67fca17dce52708f765679ec46a8553531b432d30b8da1b11b1bc89cR83-R84)

**Review by k0da — APPROVED** [review]
LGTM

File: controllers/depresolver/depresolver.go [hunk 3]
```diff
@@ -60,17 +60,19 @@ func (f LogFormat) String() string {
 }
 
 // EdgeDNSType specifies to which edge DNS is k8gb connecting
-type EdgeDNSType int
+type EdgeDNSType string
 
 const (
 	// DNSTypeNoEdgeDNS is default DNSType. Is used during integration testing when no edgeDNS provider exists
-	DNSTypeNoEdgeDNS EdgeDNSType = 1 << iota
+	DNSTypeNoEdgeDNS EdgeDNSType = "EmptyDNS"
```
Comment (somaritane) [inline controllers/depresolver/depresolver.go:67]: Makes sense to sync const values with const names here
```suggestion
	DNSTypeNoEdgeDNS EdgeDNSType = "NoEdgeDNS"
```

File: controllers/depresolver/depresolver.go [hunk 4]
```diff
@@ -60,17 +60,19 @@ func (f LogFormat) String() string {
...
-	DNSTypeInfoblox
+	DNSTypeInfoblox EdgeDNSType = "Infoblox"
 	// DNSTypeRoute53 type
-	DNSTypeRoute53
+	DNSTypeRoute53 EdgeDNSType = "Route53"
 	// DNSTypeNS1 type
-	DNSTypeNS1
+	DNSTypeNS1 EdgeDNSType = "NS1"
+	// DNSTypeMultipleProviders type
+	DNSTypeMultipleProviders EdgeDNSType = "DNSError"
```
Comment (somaritane) [inline controllers/depresolver/depresolver.go:75]: Same here, it's good to reflect const name in value:
```suggestion
	DNSTypeMultipleProviders EdgeDNSType = "MultipleProviders"
```

File: controllers/depresolver/depresolver_config.go [hunk 5]
```diff
@@ -94,6 +95,9 @@ func (dr *DependencyResolver) validateConfig(config *Config) (err error) {
 	if config.Log.Format == NoFormat {
 		return fmt.Errorf("invalid '%s', allowed values ['','%s','%s']", LogFormatKey, JSONFormat, SimpleFormat)
 	}
+	if config.EdgeDNSType == DNSTypeMultipleProviders {
+		return fmt.Errorf("several EdgeDNS recognized %s", recognisedDNSTypes)
```
Comment (somaritane) [inline controllers/depresolver/depresolver_config.go:99]: syntax correction
```suggestion
		return fmt.Errorf("several EdgeDNS recognized %s", recognizedDNSTypes)
```

**Comment by kuritka** [comment]
@somaritane, resolved, thanks

**Review by somaritane — CHANGES_REQUESTED** [review]
@kuritka, looks good, just few suggestions

**Review by somaritane — APPROVED** [review]
@kuritka LGTM

**Review by k0da — APPROVED** [review]

**Review by ytsarev — APPROVED** [review]
