### PR TITLE
Primary geotag annotation fix

### LINKED ISSUE #210: Replace k8gb.io/primarygeotag annotation with k8gb.io/primary-geotag
I know this is minor issue, and there are no strict conventions on [k8s annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/).
But `primary` and `geotag` in `k8gb.io/primarygeotag` are two separate words, so it's better to separate them with `dash` in order to make annotation more readable, avoid authoring errors, and also align with the style used by existing Ingress Controllers known to community (e.g. https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/, https://doc.traefik.io/traefik/v1.7/configuration/backends/kubernetes/#general-annotations): 
```diff
--- k8gb.io/primarygeotag
+++ k8gb.io/primary-geotag
```

### PR DESCRIPTION
**Pull request by somaritane**
This PR renames `k8gb.io/primarygeotag` annotation to `k8gb.io/primary-geotag` 
Closes #210

### CODE REVIEW

File: controllers/gslb_controller.go [hunk 1]
```diff
@@ -238,12 +242,12 @@ func (r *GslbReconciler) SetupWithManager(mgr ctrl.Manager) error {
...
 		if strategy == failoverStrategy {
 			for annotationKey, annotationValue := range a.Meta.GetAnnotations() {
-				if annotationKey == "k8gb.io/primarygeotag" {
+				if annotationKey == primaryGeoTagAnnotation {
 					gslb.Spec.Strategy.PrimaryGeoTag = annotationValue
 				}
 			}
 			if gslb.Spec.Strategy.PrimaryGeoTag == "" {
-				log.Info("k8gb.io/primarygeotag annotation is missing, skipping Gslb creation...")
+				log.Info(fmt.Sprintf("%s annotation is missing, skipping Gslb creation...", primaryGeoTagAnnotation))
```
Comment (k0da) [inline controllers/gslb_controller.go:250]: Isn't it better to use Infof() here?

**Review by k0da — CHANGES_REQUESTED** [review]
see above

**Review by kuritka — APPROVED** [review]
lgtm

File: controllers/gslb_controller.go (hunk 1 above)
Comment (somaritane) [reply controllers/gslb_controller.go:250]: Makes sense, @k0da, but we also should maintain consistency, and rest of the code uses `Info(fmt.Sprintf())`, not `Infof()`.
If you're OK, I can make the proposed replacement (35 changes in 5 files) as separate PR.

Comment (kuritka) [reply controllers/gslb_controller.go:250]: @somaritane, good point for sure! If you decide to reactor, please can you check log.Error, log.Debug ,etc... We can do all at once.

Comment (kuritka) [reply controllers/gslb_controller.go:250]: Maybe we can do in separate PR.

**Review by k0da — APPROVED** [review]

File: controllers/gslb_controller.go (hunk 1 above)
Comment (k0da) [reply controllers/gslb_controller.go:250]: @somaritane ack

Comment (somaritane) [reply controllers/gslb_controller.go:250]: Also, after carefully looking, this `log` is of `logr.Logger` type, [logr](https://pkg.go.dev/github.com/go-logr/logr) package  doesn't have functions like `Infof()` or `Errorf()`, instead you should use `Info()` and `Error()` with structured logging format e.g.:
```diff
--- log.Errorf("unable to reconcile object %s/%s: %v", object.Namespace, object.Name, err)
+++ log.Error(err, "unable to reconcile object", "object", object)
```
